# Generated by Django 5.0.6 on 2024-08-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='test_type',
        ),
    ]
