# Generated by Django 5.0.6 on 2024-08-13 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_booking_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='test_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.testtype'),
            preserve_default=False,
        ),
    ]
