# Generated by Django 5.0.6 on 2024-08-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_booking_test_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='test_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='test_types',
            field=models.ManyToManyField(to='myapp.testtype'),
        ),
    ]
